# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

app_sample:
    path: /hello
    defaults:
        _controller: AppBundle:Default:hello

#app_api_supplier:
#    prefix: /api
#    resource: |
#        name: app.supplier
#    type: sylius.resource_api

app_special_offer_show:
    path: /special-offer/{productSlug}
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            repository:
                method: findOneForSpecialOffer
                arguments:
                    - $productSlug
                    - 'expr:service("sylius.context.channel").getChannel()'
            template: AppBundle:Product:specialOffer.html.twig

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

